Repository microsoft/win-student-devs, pull requests merged in 2022-03, with the labels that each got.

#64 Developer Tools week 3 day 3 update
  docs/30DaysOfPWA/dev-tools/03.md
  docs/30DaysOfPWA/dev-tools/04.md
  docs/30DaysOfPWA/dev-tools/_media/app-available-icon.png
  docs/30DaysOfPWA/dev-tools/_media/cache-storage.png
  docs/30DaysOfPWA/dev-tools/_media/device-mode.png
  docs/30DaysOfPWA/dev-tools/_media/installability-warnings.png
  docs/30DaysOfPWA/dev-tools/_media/offline-mode.png
  docs/30DaysOfPWA/dev-tools/_media/service-worker-debug.png
  docs/30DaysOfPWA/dev-tools/_media/service-worker-status.png
Labels: week-3, ready to merge

#61 Add discussion and feedback links to sidebar
  docs/_sidebar.md
  docs/index.html
Labels: gh-pg maintenance

#67 Developer Tools week 3 day 5 update
  docs/30DaysOfPWA/dev-tools/05.md
  docs/30DaysOfPWA/dev-tools/_media/05/enter-url.png
  docs/30DaysOfPWA/dev-tools/_media/05/icon-on-left.png
  docs/30DaysOfPWA/dev-tools/_media/05/lighthouse.png
  docs/30DaysOfPWA/dev-tools/_media/05/pwa-studio.png
  docs/30DaysOfPWA/dev-tools/_media/05/report-card.jpeg
  docs/30DaysOfPWA/dev-tools/_media/05/total-score.png
  docs/30DaysOfPWA/dev-tools/_media/05/webhint.png
Labels: week-3, ready to merge

#72 Week 3 / Day 6 / Test Automation
  docs/30DaysOfPWA/dev-tools/06.md
  docs/30DaysOfPWA/dev-tools/_media/6-hello-playwright.jpg
  docs/30DaysOfPWA/dev-tools/_media/6-playwright-report-detail.png
  docs/30DaysOfPWA/dev-tools/_media/6-playwright-report.png
  docs/30DaysOfPWA/dev-tools/_media/6-test-pyramid.png
Labels: week-3, ready to merge

#55 Dev Tools week 3 day 7 update
  docs/30DaysOfPWA/dev-tools/07.md
  docs/30DaysOfPWA/dev-tools/_media/07_pc.png
  docs/30DaysOfPWA/dev-tools/_media/07_pwabuilder_home.png
  docs/30DaysOfPWA/dev-tools/_media/07_pwabuilder_pub.png
  docs/30DaysOfPWA/dev-tools/_media/07_pwabuilder_rc.png
  docs/30DaysOfPWA/dev-tools/_media/07_store.png
Labels: week-3, ready to merge

#66 Week 4 Day 1: Best Practices for Installability
  docs/30DaysOfPWA/platforms-practices/01.md
  docs/30DaysOfPWA/platforms-practices/_media/twitter-in-store.png
  docs/30DaysOfPWA/platforms-practices/_media/twitter-offline.png
  docs/30DaysOfPWA/platforms-practices/_media/twitter-push.jpg
  docs/30DaysOfPWA/platforms-practices/_media/twitter-pwa.png
Labels: week-4, ready to merge, needs: creatives

#69 Week 4 Day 2 update
  docs/30DaysOfPWA/platforms-practices/02.md
  docs/feed.xml
Labels: week-4, ready to merge

#81 Update Week 4 Table of Contents
  docs/30DaysOfPWA/platforms-practices/README.md
Labels: week-4, needs: review

#79 Article for distributing your PWA (4.3)
  docs/30DaysOfPWA/platforms-practices/03.md
Labels: week-4, ready to merge

#73 Week 4 Day 4 Update: Reliability
  docs/30DaysOfPWA/platforms-practices/04.md
Labels: week-4, ready to merge

#74 Week 4 Day 5 update: web components
  docs/30DaysOfPWA/platforms-practices/05.md
  docs/30DaysOfPWA/platforms-practices/_media/component-web-standards.png
  docs/30DaysOfPWA/platforms-practices/_media/movie-review.png
Labels: week-4, ready to merge

#76 Week 4 Day 7 PWA UI UX
  docs/30DaysOfPWA/platforms-practices/07.md
  docs/30DaysOfPWA/platforms-practices/_media/starbucks-app.jpg
  docs/30DaysOfPWA/platforms-practices/_media/twitter-app.jpg
Labels: week-4

#82 Add summary article
  docs/30DaysOfPWA/summary.md
Labels: needs: review
