Repository microsoft/win-student-devs, pull requests merged in 2022-02, with the labels that each got.

#28 Core Concepts week 1 day 2 updated
  docs/30DaysOfPWA/core-concepts/01.md
  docs/30DaysOfPWA/core-concepts/02.md
  docs/30DaysOfPWA/core-concepts/_media/deconstruct-pwa.png
Labels: week-1

#29 Core Concepts week 1 day 3 update
  docs/30DaysOfPWA/core-concepts/03.md
  docs/30DaysOfPWA/core-concepts/_media/3-manifest.png
Labels: week-1

#33 Core Concepts week 1 day 4 update
  docs/30DaysOfPWA/core-concepts/04.md
  docs/30DaysOfPWA/core-concepts/_media/4-service-workers.png
Labels: week-1

#39 Core Concept week 1 day 5 update
  docs/30DaysOfPWA/core-concepts/05.md
Labels: week-1, ready to merge

#37 Add badges to main readme page
  docs/README.md
Labels: 30days, gh-pg maintenance

#41 Core Concept week 1 day 6 update
  docs/30DaysOfPWA/core-concepts/06.md
  docs/30DaysOfPWA/core-concepts/_media/6-capabilities.png
Labels: week-1, ready to merge

#44 Core Concepts week 1 day 7 update
  docs/30DaysOfPWA/core-concepts/07.md
  docs/30DaysOfPWA/core-concepts/_media/lighthous-local-mobile-pwa.png
  docs/30DaysOfPWA/core-concepts/_media/lighthouse-local-desktop-pwa.png
  docs/30DaysOfPWA/core-concepts/_media/lighthouse-local-desktop.png
  docs/30DaysOfPWA/core-concepts/_media/lighthouse-local-mobile.png
  docs/30DaysOfPWA/core-concepts/_media/lighthouse-swa-desktop-pwa.png
  docs/30DaysOfPWA/core-concepts/_media/lighthouse-swa-desktop.png
  docs/30DaysOfPWA/core-concepts/_media/pwa-installed.png
  docs/30DaysOfPWA/core-concepts/_media/pwabuilder-audit.png
  docs/30DaysOfPWA/core-concepts/_media/pwabuilder-final.png
  docs/30DaysOfPWA/core-concepts/_media/pwabuilder-manifest.png
Labels: week-1, ready to merge

#21 Advanced Capabilities week 2 day 1 update
  docs/30DaysOfPWA/advanced-capabilities/01.md
Labels: week-2, ready to merge

#35 Advanced Capabilities week 2 day 2 update
  docs/30DaysOfPWA/advanced-capabilities/02.md
  docs/30DaysOfPWA/advanced-capabilities/_media/day-02-01.jpg
Labels: week-2, needs: review

#48 Advanced Capabilities week 2 day 3 update
  docs/30DaysOfPWA/advanced-capabilities/03.md
  docs/30DaysOfPWA/advanced-capabilities/_media/day-03/pwinter-share-target.jpg
  docs/30DaysOfPWA/advanced-capabilities/_media/day-03/pwinter-share.jpg
  docs/30DaysOfPWA/advanced-capabilities/_media/day-03/pwinter.jpg
  docs/30DaysOfPWA/advanced-capabilities/_media/day-03/sharing-edge.jpg
  docs/30DaysOfPWA/advanced-capabilities/_media/day-03/sharing-mac.jpg
  docs/30DaysOfPWA/advanced-capabilities/_media/day-03/sharing-mobile.jpg
Labels: week-2, ready to merge

#25 Added info to tables for week 4.
  docs/30DaysOfPWA/platforms-practices/01.md
  docs/30DaysOfPWA/platforms-practices/02.md
  docs/30DaysOfPWA/platforms-practices/03.md
  docs/30DaysOfPWA/platforms-practices/04.md
  docs/30DaysOfPWA/platforms-practices/05.md
  docs/30DaysOfPWA/platforms-practices/06.md
  docs/30DaysOfPWA/platforms-practices/07.md
  docs/30DaysOfPWA/platforms-practices/README.md
  docs/30DaysOfPWA/platforms-practices/_media/day1.png
  docs/30DaysOfPWA/platforms-practices/_media/day2.png
  docs/30DaysOfPWA/platforms-practices/_media/day3.png
  docs/30DaysOfPWA/platforms-practices/_media/day4.png
  docs/30DaysOfPWA/platforms-practices/_media/day5.png
  docs/30DaysOfPWA/platforms-practices/_media/day6.png
  docs/30DaysOfPWA/platforms-practices/_media/day7.png
Labels: week-4

#36 Making the gh-pg site a PWA
  docs/index.html
  docs/manifest.json
  docs/sw.js
Labels: 30days, gh-pg maintenance

#43 Advanced Capabilities week 2 day 4 update
  docs/30DaysOfPWA/advanced-capabilities/04.md
  docs/30DaysOfPWA/advanced-capabilities/_media/display-desktop.png
  docs/30DaysOfPWA/advanced-capabilities/_media/display-fullscreen.png
  docs/30DaysOfPWA/advanced-capabilities/_media/display-minimal-ui.png
  docs/30DaysOfPWA/advanced-capabilities/_media/display-spec-wco.png
  docs/30DaysOfPWA/advanced-capabilities/_media/display-standalone.png
Labels: week-2, ready to merge

#49 Advanced Capabilities week 2 day 5 update
  docs/30DaysOfPWA/advanced-capabilities/05.md
Labels: week-2, ready to merge

#50 Advanced Capabilities week 2 day 6 update
  docs/30DaysOfPWA/advanced-capabilities/06.md
  docs/30DaysOfPWA/advanced-capabilities/_media/background-sync-devtools-record.png
  docs/30DaysOfPWA/advanced-capabilities/_media/background-sync-devtools-send.png
  docs/30DaysOfPWA/advanced-capabilities/_media/background-sync-permission.png
Labels: week-2, ready to merge

#56 Developer Tools week 3 day 1 update
  docs/30DaysOfPWA/dev-tools/01.md
  docs/30DaysOfPWA/dev-tools/_media/icon-on-left.png
  docs/30DaysOfPWA/dev-tools/_media/new-app.png
  docs/30DaysOfPWA/dev-tools/_media/pwa-starter.png
  docs/30DaysOfPWA/dev-tools/_media/pwa-studio.png
  docs/30DaysOfPWA/dev-tools/_media/start-new-pwa.png
Labels: week-3, ready to merge

#58 Developer Tools week 3 day 2 update
  docs/30DaysOfPWA/dev-tools/02.md
  docs/30DaysOfPWA/dev-tools/_media/02/Icon_Screenshot_3.png
  docs/30DaysOfPWA/dev-tools/_media/02/Publish_5.png
  docs/30DaysOfPWA/dev-tools/_media/02/Report_card_page_2.png
  docs/30DaysOfPWA/dev-tools/_media/02/SWPage_4.png
  docs/30DaysOfPWA/dev-tools/_media/02/homepage.png
Labels: week-3, ready to merge
